### ISSUE TITLE
Default Proposer Fee error on beacon chain startup

### ISSUE THREAD

**Issue by alexpeterson91** [dappnode/DAppNodePackage-teku#34]
**Describe the bug**

Teku's beacon-chain when started always throws an error about using a remote signer but not having a default proposal fee address entered. 
`2022-11-24 19:35:59.143 WARN  - Rest API is enabled but no default fee recipient has been configured via the validators-proposer-default-fee-recipient option! It is strongly recommended to configure it to avoid possible block production failures in case the node has not been prepared for potential proposers by the Validator Client.
`

**To Reproduce**

Install any Teku Client for any chain, it happens on all currently, set the appropriate config values including the default proposer recipient address, start the package or restart if already running and it will throw this error in the beacon-chain logs.

**Expected behavior**
We shouldn't see this error as we have set the proposer default fee address in the setup wizard/config. 

Will be fixed by adding 
`--validators-proposer-default-fee-recipient="${FEE_RECIPIENT_ADDRESS}"` to the beacon-chain entry point.

**DAppNode version:**
All currently published versions of Teku (Chiado is fixed)

**Additional context**
Was able to stop the error by adding 
`--validators-proposer-default-fee-recipient=<ADDRESS>` to the EXTRA_OPTS field of the Beacon-chain.  This stopped the error from recurring. docs below aren't super clear but it seems in some rare/edge cases (running multiple validators from one beacon chain), the beacon-chain in addition to the validator wants to see this value because it may provide it to the validator if the validator doesn't for some reason.  Regardless it's a simple fix to implement the same  flag for the entrypoint on the beacon chain as well as it is on the validator.
https://docs.teku.consensys.net/en/latest/Reference/CLI/CLI-Syntax/#validators-proposer-default-fee-recipient

### Must Be Fixed for:

- [ ] Teku Mainnet (this repo)
- [x] dappnode/DAppNodePackage-teku-prater#96
- [ ] dappnode/DAppNodePackage-teku-gnosis#38
- [x] dappnode/DAppNodePackage-teku-chiado#13
- [x] dappnode/DNP_DAPPMANAGER#1258
